# helm/values/jenkins-values.yaml
controller:
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  persistence:
    enabled: true
    storageClass: "standard"
    size: "8Gi"

# Add this entire 'agent' section
agent:
  # Define the Kubernetes cloud configuration
  kubernetes:
    # The name of the cloud in Jenkins UI
    name: kubernetes
    # The namespace where Jenkins controller runs
    namespace: infra
    # The internal URL for Jenkins
    jenkinsUrl: http://jenkins.infra.svc.cluster.local:8080
    # The ID of the credential we will create later
    credentialsId: kubernetes-jenkins-agent
    # Define the build agent pod templates
    podTemplates:
      # Name of the first pod template
      maven-agent:
        # A label for pipelines to select this agent
        label: jenkins-maven-agent
        # The namespace where agent pods will be created
        namespace: apps
        # Define the containers inside the agent pod
        containers:
        - name: jnlp
          image: jenkins/inbound-agent:latest-jdk17
          workingDir: /home/jenkins/agent
          alwaysPullImage: true
        - name: maven
          image: maven:3.9.6-eclipse-temurin-17
          command: cat
          ttyEnabled: true
          alwaysPullImage: true